/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dllsss_Aop */

#ifndef _Included_dllsss_Aop
#define _Included_dllsss_Aop
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     dllsss_Aop
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_dllsss_Aop_add
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     dllsss_Aop
 * Method:    sub
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_dllsss_Aop_sub
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     dllsss_Aop
 * Method:    mul
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_dllsss_Aop_mul
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     dllsss_Aop
 * Method:    div
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_dllsss_Aop_div
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
